￼
type Course{
  id: ID!
  title: String!
  description: String!
  image: String!
  price: Number!
}

type Query {
  getUser(id: ID!): Course
}

input CreateCourseInput {
  title: String!
  description: String!
  image: String!
  price: Number!
}

type Mutation {
  createCourse(input: CreateCourseInput!): Course!
}

